In [11]:
import pandas as pd

# Load the CSV file
file_path = "../../Cleaned Data/fullcoffeeshops.csv"  
business_data = pd.read_csv(file_path)

restaurants_df = pd.read_csv("riyadh_restaurants.csv")
coffeeshops_df = pd.read_csv("riyadh_coffeeshops.csv")

combined_df = pd.concat([coffeeshops_df, restaurants_df], ignore_index=True)

# Remove records where Popularity is 'No popularity data'
combined_df = combined_df[combined_df['Popularity'] != 'No popularity data']

In [12]:
combined_df

,Business ID,Name,Latitude,Longitude,Category,Rating,Popularity
0,5a05a3f947f8763f72dcb7d4,Java Time (جافا تايم),24.678579,46.648438,Coffee Shop,9.0,0.9886785274263029
1,565391dc498e758480887395,ستاربكس,24.686561,46.649476,Coffee Shop,7.5,0.9320658309495067
2,6005c3e67515ea1d8d94c33c,KYAN (كيان),24.688150,46.650505,Coffee Shop,7.3,0.9867299825235434
3,612e97694da17566d4a587e9,Java Time,24.679884,46.654387,Café,8.0,0.15829616104652505
4,600ecb011278de21986c9c36,كيان العينين,24.688110,46.650701,Café,No rating,0.47169720750047556
...,...,...,...,...,...,...,...
8104,4eb7b92f5c5c5a5320f8fae5,Ib Yemeni. Restaurant,24.668167,46.724258,Restaurant,No rating,0.6975275169742085
8105,5bdfe3efe17910002ca02559,الرومانسية,24.668295,46.723913,Arepa Restaurant,No rating,0.25590830460592634
8106,4fa9f499e4b04c40ca2db552,بيتزا هت,24.668565,46.724015,Pizzeria,No rating,0.7145559504401116
8107,6367f98a6951774c59e3841d,Ulb,24.661563,46.727033,Fast Food Restaurant,No rating,0.9756627452793122
8108,6186c5582d797f2bf4da0b32,Tikka Restaurant,24.670558,46.729509,Indian Restaurant,No rating,0.943061953416265

In [13]:
combined_df.dtypes

Business ID     object
Name            object
Latitude       float64
Longitude      float64
Category        object
Rating          object
Popularity      object
dtype: object

#### Duplicates

In [14]:
combined_df = combined_df.drop_duplicates(subset=['Business ID'])

In [15]:
combined_df

,Business ID,Name,Latitude,Longitude,Category,Rating,Popularity
0,5a05a3f947f8763f72dcb7d4,Java Time (جافا تايم),24.678579,46.648438,Coffee Shop,9.0,0.9886785274263029
1,565391dc498e758480887395,ستاربكس,24.686561,46.649476,Coffee Shop,7.5,0.9320658309495067
2,6005c3e67515ea1d8d94c33c,KYAN (كيان),24.688150,46.650505,Coffee Shop,7.3,0.9867299825235434
3,612e97694da17566d4a587e9,Java Time,24.679884,46.654387,Café,8.0,0.15829616104652505
4,600ecb011278de21986c9c36,كيان العينين,24.688110,46.650701,Café,No rating,0.47169720750047556
...,...,...,...,...,...,...,...
8010,4ed2a926b8f7971d6d5a3bc3,Al Khafeef (عالخفيف),24.666398,46.724671,Pizzeria,8.2,0.9395684399729053
8022,52723012498e732201ce5928,فرن و ملحمة و مشويات الضيعة اللبنانية,24.669561,46.722548,Middle Eastern Restaurant,7.0,0.7493950799241206
8040,5209e35611d2957a607f06c2,بوفيه فول وفلافل,24.669747,46.722492,Falafel Restaurant,No rating,0.49907639682756977
8055,6168fd0c3f650f36a7143510,Zam Zam Indian Restaurant,24.668545,46.713180,Indian Restaurant,No rating,0.11504237551802671
8058,5425a4bc498e30cf770eb0fa,Nomania Cafe,24.669182,46.713032,Indian Chinese Restaurant,No rating,0.7716824511841499

#### Variance

In [17]:
# Convert 'Popularity' column to numeric (ignore errors for non-numeric values)
combined_df["Popularity"] = pd.to_numeric(combined_df["Popularity"], errors="coerce")

# Calculate variance
variance = combined_df["Popularity"].var()

# Print result
print(f"Variance of Popularity: {variance}")

Variance of Popularity: 0.08945623214560175

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17036\36137619.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df["Popularity"] = pd.to_numeric(combined_df["Popularity"], errors="coerce")

#### After scaling

In [18]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
popularity_scaled = scaler.fit_transform(combined_df[["Popularity"]])
combined_df["Popularity_Scaled"] = popularity_scaled
scaled_variance = combined_df["Popularity_Scaled"].var()

# Print the variance of the scaled values
print(f"Variance of Scaled Popularity: {scaled_variance}")

Variance of Scaled Popularity: 0.08980811240884234

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17036\2204798768.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df["Popularity_Scaled"] = popularity_scaled